#!/sd/usr/bin/python
# -*- coding: utf-8 -*-
# Build PROTECTED-BSSID lists from configured SSID patterns.
#   Reads:  /sd/bot/protect-ssids.conf  (one SSID per line; trailing '*' = prefix match; '#' comments)
#   Sources: recon.db (pineap scans) + hcx capture log + our own live AP BSSIDs
#   Writes: whitelist.lst (mdk3, AA:BB..) and hcx-protect.list (hcxdumptool, aabb.. lowercase)
import sqlite3, re, subprocess, os
CONF='/sd/bot/protect-ssids.conf'
WL='/pineapple/modules/Deauth/lists/whitelist.lst'
HL='/sd/bot/hcx-protect.list'
DB='/sd/recon.db'
LOG='/sd/handshakes/hcx-status.log'
OUR_IFACES=['wlan0','wlan2-1']

def norm(m):
    m=(m or '').replace(':','').replace('-','').lower()
    return m if re.match(r'^[0-9a-f]{12}$', m) else None

pats=[]
try:
    for line in open(CONF):
        s=line.split('#')[0].strip()
        if s: pats.append(s)
except Exception:
    pass

def match(ssid):
    for p in pats:
        if p.endswith('*'):
            if ssid.startswith(p[:-1]): return p
        elif ssid==p:
            return p
    return None

res={}
for p in pats: res[p]=set()

try:
    c=sqlite3.connect(DB)
    for ssid,bssid in c.execute("select ssid,bssid from aps"):
        p=match(ssid or '')
        if p:
            n=norm(bssid)
            if n: res[p].add(n)
except Exception:
    pass

try:
    rx=re.compile(r'<-[->] ([0-9a-f]{12}) .*\(([^)]*)\)\s*$')
    for line in open(LOG):
        m=rx.search(line)
        if m:
            p=match(m.group(2))
            if p:
                n=norm(m.group(1))
                if n: res[p].add(n)
except Exception:
    pass

# Build the full protected-BSSID set FIRST, independent of any file write, so a
# failure writing the (optional) mdk3 list can never leave the hcx filter empty.
allm=set()
for p in pats:
    for n in res[p]: allm.add(n)
# always protect our own APs
for ifc in OUR_IFACES:
    try:
        out=subprocess.Popen(['iwinfo',ifc,'info'],stdout=subprocess.PIPE,stderr=subprocess.PIPE).communicate()[0]
        mm=re.search(r'Access Point:\s*([0-9A-Fa-f:]{17})', out)
        n=norm(mm.group(1)) if mm else None
        if n: allm.add(n)
    except Exception:
        pass

# hcxdumptool filter (critical for deauth safety) — /sd/bot always exists; write it FIRST.
try: os.makedirs('/sd/bot')
except OSError: pass
h=open(HL,'w')
for n in sorted(allm): h.write(n+"\n")
h.close()

# mdk3 whitelist (best-effort; its directory only exists if the Deauth module is installed).
try:
    try: os.makedirs(os.path.dirname(WL))
    except OSError: pass
    w=open(WL,'w')
    w.write("# ==== PROTECTED networks (never deauthed). mdk3 whitelist / hcx filtermode=1 ====\n")
    w.write("# Auto-generated by wl-refresh.py from protect-ssids.conf + recon.db + capture log + our APs.\n\n")
    for p in pats:
        w.write("# %s\n" % p)
        for n in sorted(res[p]):
            w.write(':'.join(n[i:i+2] for i in range(0,12,2)).upper()+"\n")
    w.close()
except Exception:
    pass
print "protected: %d BSSIDs from %d SSID patterns" % (len(allm), len(pats))
